import * as Print from 'expo-print';
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Sharing from 'expo-sharing';
import { useEffect, useState } from "react";
import {
    ActivityIndicator,
    Alert,
    Image,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from "react-native";
import {
    getDonationImpactDetail,
    getUserProfile,
} from "../../../services/api";
import { colors } from "../../../theme/colors";
import { getImageUrl } from "../../../utils/imageHelper";

export default function DonationReceiptScreen() {
    const router = useRouter();
    const { transactionID } = useLocalSearchParams<{ transactionID: string }>();
    const [loading, setLoading] = useState(true);
    const [downloading, setDownloading] = useState(false);
    const [data, setData] = useState<any>(null);
    const [userProfile, setUserProfile] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        loadData();
    }, [transactionID]);

    const loadData = async () => {
        if (!transactionID) return;
        setLoading(true);
        try {
            setError(null);
            const [detailsData, userData] = await Promise.all([
                getDonationImpactDetail(Number(transactionID)),
                getUserProfile(),
            ]);

            setData(detailsData);
            setUserProfile(userData);

        } catch (err: any) {
            console.error("Error loading data:", err);
            setError("Failed to load information.");
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadCertificate = async () => {
        if (!data || !userProfile) {
            Alert.alert("Error", "Data not fully loaded. Please try again.");
            return;
        }
        setDownloading(true);

        try {
            const htmlContent = `
        <html>
          <body style="padding: 40px; font-family: Helvetica, sans-serif; text-align: center; border: 10px solid #004d40;">
            <div style="padding: 20px;">
              <h1 style="color: #004d40; font-size: 36px; margin-bottom: 20px;">Certificate of Appreciation</h1>
              
              <p style="font-size: 20px; color: #555; margin-bottom: 30px;">This certificate is proudly presented to</p>
              
              <h2 style="font-size: 32px; margin: 20px 0; color: #222; text-decoration: underline;">
                ${userProfile.name || "Valued Donor"}
              </h2> 
              
              <p style="font-size: 18px; line-height: 1.8; margin-top: 30px;">
                in recognition of your kind contribution of <b style="color: #004d40;">RM${data.donationAmount.toFixed(2)}</b><br/>
                towards the <b>SavePaws Animal Rescue and Welfare Fund</b>.
              </p>
              
              <p style="font-size: 16px; color: #666; margin: 30px 0; font-style: italic;">
                "Your generosity supports ongoing rescue efforts, medical care,<br/> 
                and sheltering of animals in need."
              </p>
              
              <div style="margin-top: 60px; display: flex; justify-content: space-between; padding: 0 40px;">
                <div style="text-align: center;">
                  <p style="margin: 0; font-weight: bold;">${new Date(data.donationDate).toLocaleDateString()}</p>
                  <div style="border-top: 1px solid #333; width: 150px; margin: 5px auto 0;"></div>
                  <p style="font-size: 14px; margin-top: 5px; color: #555;">Date</p>
                </div>
                
                <div style="text-align: center;">
                  <p style="margin: 0; font-family: 'Courier New', cursive; font-size: 18px;">SavePaws</p>
                  <div style="border-top: 1px solid #333; width: 150px; margin: 5px auto 0;"></div>
                  <p style="font-size: 14px; margin-top: 5px; color: #555;">Authorized Signatory</p>
                </div>
              </div>
              
              <p style="margin-top: 50px; font-size: 10px; color: #aaa;">
                Generated by SavePaws App | Transaction ID: ${data.transactionID}
              </p>
            </div>
          </body>
        </html>
      `;

            const { uri } = await Print.printToFileAsync({ html: htmlContent });

            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri, {
                    UTI: '.pdf',
                    mimeType: 'application/pdf',
                    dialogTitle: `Download Certificate - ${userProfile.name || 'Donor'}`
                });
            } else {
                Alert.alert("Success", "Certificate generated!");
            }

        } catch (error) {
            console.error("Certificate error:", error);
            Alert.alert("Error", "Could not generate certificate.");
        } finally {
            setDownloading(false);
        }
    };

    if (loading) {
        return (
            <View style={styles.loadingContainer}>
                <ActivityIndicator size="large" color={colors.primary} />
                <Text style={styles.loadingText}>Loading receipt...</Text>
            </View>
        );
    }

    if (error || !data) {
        return (
            <View style={styles.errorContainer}>
                <Text style={styles.errorText}>{error || "Could not load information."}</Text>
                <TouchableOpacity
                    style={styles.backButton}
                    onPress={() => router.back()}
                >
                    <Text style={styles.backButtonText}>Go Back</Text>
                </TouchableOpacity>
            </View>
        );
    }

    const formatDate = (dateString: string) => {
        const date = new Date(dateString);
        return date.toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
        });
    };

    return (
        <ScrollView style={styles.container}>
            {/* Animal Info Card */}
            <View style={styles.animalCard}>
                <Image
                    source={{ uri: getImageUrl(data.animalPhotoURL) }}
                    style={styles.animalImage}
                />
                <View style={styles.animalInfo}>
                    <Text style={styles.animalName}>{data.animalName}</Text>
                    <Text style={styles.animalType}>{data.animalType}</Text>
                    <Text style={styles.receiptLabel}>Transaction Receipt</Text>
                </View>
            </View>

            {/* Donation Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Donation Summary</Text>
                <View style={styles.summaryRow}>
                    <Text style={styles.summaryLabel}>Amount Donated</Text>
                    <Text style={styles.summaryValue}>
                        ${data.donationAmount.toFixed(2)}
                    </Text>
                </View>
                <View style={styles.summaryRow}>
                    <Text style={styles.summaryLabel}>Date</Text>
                    <Text style={styles.summaryValue}>{formatDate(data.donationDate)}</Text>
                </View>
                <View style={styles.summaryRow}>
                    <Text style={styles.summaryLabel}>Transaction ID</Text>
                    <Text style={styles.summaryValue}>#{data.transactionID}</Text>
                </View>
            </View>

            {/* Download Certificate Button */}
            <TouchableOpacity
                style={[styles.downloadButton, downloading && styles.downloadButtonDisabled]}
                onPress={handleDownloadCertificate}
                disabled={downloading}
            >
                {downloading ? (
                    <ActivityIndicator color={colors.surface} />
                ) : (
                    <Text style={styles.downloadButtonText}>Download Certificate</Text>
                )}
            </TouchableOpacity>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: colors.background },
    loadingText: { marginTop: 12, fontSize: 16, color: colors.textSecondary },
    errorContainer: { flex: 1, justifyContent: "center", alignItems: "center", padding: 20, backgroundColor: colors.background },
    errorText: { fontSize: 16, color: colors.danger, textAlign: "center", marginBottom: 20 },
    backButton: { backgroundColor: colors.primary, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
    backButtonText: { color: colors.surface, fontSize: 16, fontWeight: "600" },
    animalCard: { backgroundColor: colors.surface, margin: 16, borderRadius: 12, overflow: "hidden", elevation: 2 },
    animalImage: { width: "100%", height: 200, resizeMode: "cover" },
    animalInfo: { padding: 16 },
    animalName: { fontSize: 24, fontWeight: "bold", color: colors.textPrimary, marginBottom: 4 },
    animalType: { fontSize: 16, color: colors.textSecondary },
    receiptLabel: { fontSize: 14, color: colors.primary, fontWeight: '700', marginTop: 8, textTransform: 'uppercase' },
    section: { backgroundColor: colors.surface, margin: 16, marginTop: 0, padding: 16, borderRadius: 12, elevation: 2 },
    sectionTitle: { fontSize: 20, fontWeight: "bold", color: colors.textPrimary, marginBottom: 16 },
    summaryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
    summaryLabel: { fontSize: 16, color: colors.textSecondary },
    summaryValue: { fontSize: 16, fontWeight: "600", color: colors.textPrimary },
    downloadButton: { backgroundColor: colors.primary, margin: 16, marginTop: 0, padding: 16, borderRadius: 12, alignItems: "center" },
    downloadButtonDisabled: { opacity: 0.7 },
    downloadButtonText: { color: colors.surface, fontSize: 18, fontWeight: "bold" },
});
